!!com.compuware.ispw.cli.model.IspwRoot
ispwApplication:
  application: RXN1
  host: cwcc.compuware.com
  pathMappings:
  - path: \AMAC
    types:
    - fileExtension: amac
      ispwType: AMAC
  - path: \C
    types:
    - fileExtension: c
      ispwType: C
  - path: \CLST
    types:
    - fileExtension: clst
      ispwType: CLST
  - path: \COB
    types:
    - fileExtension: cbl
      ispwType: COB
  - path: \H
    types:
    - fileExtension: h
      ispwType: H
  - path: \COPY
    types:
    - fileExtension: cpy
      ispwType: DCL
  - path: \ASM
    types:
    - fileExtension: asm
      ispwType: PWS
  - path: \INCL
    types:
    - fileExtension: incl
      ispwType: INCL
  - path: \JOB
    types:
    - fileExtension: jcl
      ispwType: JOBH
  - path: \PLI
    types:
    - fileExtension: pli
      ispwType: PLI
  - path: \.settings
    types:
    - fileExtension: prefs
      ispwType: TPRF
  port: 16196
  runtimeConfig: ISPW
  stream: FTSDEMO
